//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_Car.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_bookings
    {
        public int booking_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> car_booked { get; set; }

        [Required]
        public string pickup_location { get; set; }

        [Required]
        public string return_location { get; set; }

        [Required]
        public Nullable<System.DateTime> pickup_datetime { get; set; }

        [Required]
        public Nullable<System.DateTime> return_datetime { get; set; }


        public Nullable<decimal> sub_total { get; set; }
        public Nullable<System.DateTime> booked_at { get; set; }
    
        public virtual tb_cars tb_cars { get; set; }
        public virtual tb_users tb_users { get; set; }
    }
}
