//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_Car.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_users()
        {
            this.tb_bookings = new HashSet<tb_bookings>();
        }
    
        public int user_id { get; set; }

        [Required(ErrorMessage = "Please enter your name.")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Name cannot be longer than 100 characters")]
        public string user_name { get; set; }


        [Required(ErrorMessage = "Please enter contact number.")]
        [StringLength(15, MinimumLength = 1, ErrorMessage = "Contact number cannot be longer than 15 characters")]
        [RegularExpression(@"[0][3][0-9]{2}[\-]?[0-9]{7}", ErrorMessage = "Correct format is: 0333(-)3333333.")]
        public string contact_num { get; set; }


        [Required(ErrorMessage = "Please enter email address.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Email address must be at least 5 characters long and cannot be longer than 50 characters")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string email_address { get; set; }


        [Required(ErrorMessage = "Please enter password.")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "password cannot be longer than 20 characters")]
        public string user_password { get; set; }


        [Required(ErrorMessage = "Please re-enter password")]
        [Compare("user_password", ErrorMessage = "Password does not match")]
        public string confirm_password { get; set; }


        [Required(ErrorMessage = "Please enter your address.")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Address cannot be longer than 50 characters")]
        public string user_address { get; set; }


        [Required(ErrorMessage = "Please select gender.")]
        public string gender { get; set; }


        public string role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_bookings> tb_bookings { get; set; }
    }
}
